### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by 32Red** [sSteps1s/Netherwart-Macro#1]
I don't know how to run this file.

**Comment by 32Red** [comment]
Okay I ran it but how do I enable the macro

**Comment by maxsonchen** [comment]
Try Ctrl-Z

**Comment by 32Red** [comment]
Pressing Ctrl - and Z? Because that didn't work

**Comment by maxsonchen** [comment]
Yes, pressing ctrl and Z after you are running the program should work

**Comment by maxsonchen** [comment]
After you start the macro this should appear in your taskbar. If you right click the green H you can press reload script. Then when you are in game you can press Ctrl-Z and it should work.
![Screenshot 2021-09-22 164729](https://user-images.githubusercontent.com/84909844/134295790-74adc410-1fc3-4b70-8b59-720df3904365.png)

**Comment by 32Red** [comment]
You're a life saver!

**Comment by 32Red** [comment]
It worked for a second and then when I paused it.. it didn't work

**Comment by 32Red** [comment]
Okay I think I figured it out, but it doesn't switch from holding A and W to D and W ?

**Comment by maxsonchen** [comment]
After you pause it you have to reload it again. The script automatically swaps from AW to DW but you need to have a vertical nether wart farm. This script was also designed with specific timings for the specific speed with rancher boots and the length of the farm. You will need to change the timings accordingly.

**Comment by 32Red** [comment]
I switched the time to exactly how the whole farm but it just doesn't switch

**Comment by maxsonchen** [comment]
How long does it take you to go from one side of the farm to the other? In seconds

**Comment by 32Red** [comment]
51 seconds

**Comment by 32Red** [comment]
with 100% speed holding w and d

**Comment by maxsonchen** [comment]
In the code replace both of he sleep which is 28,000 with 51,000

**Comment by 32Red** [comment]
I did that but it just doesn't switch from wa to wd

**Comment by maxsonchen** [comment]
Can u show a video so i can view ur issue

**Comment by fractured345** [comment]
can yo uhelp me
