### ISSUE TITLE
doesn't run properly

### ISSUE THREAD

**Issue by tricckel** [sSteps1s/Netherwart-Macro#3]
so i dl'd it and it worked fine for the first row, changed the time to 32000 for my farm, it does the first row completely fine, and then it doesn't do the second row at all. please help

**Comment by maxsonchen** [comment]
Change the 
\
`Loop, 2`

Section to

`Loop, Amount of times you layers your farm has`

**Comment by tricckel** [comment]
my farm is technically infinite so do i jsut put in a really big number?

**Comment by tricckel** [comment]
this is the code


CtrlZ := Chr(26) 
Input, OutputVar, L1 M
if (OutputVar = CtrlZ)	
Loop 1000
{
Send, {LButton Down}{d down}
Sleep, 32000
Send, {LButton Up}{d up}

Send, {LButton Down}{a down}
Sleep, 32000
Send, {LButton Up}{a up}
}

**Comment by tricckel** [comment]
it doesnt work

**Comment by maxsonchen** [comment]
You need to indent all of the "Send". And remember you have to activate it with Ctrl Z

**Comment by sSteps1s** [comment]
CtrlZ := Chr(26) ; Store the character for Ctrl-C in the CtrlC var.
Input, OutputVar, L1 M
if (OutputVar = CtrlZ)	
Loop, 1000
{
	Send, {LButton Down}{w down}{d down}
	Sleep, x
	Send, {LButton Up}{w up}{d up}

	Send, {LButton Down}{w down}{a down}
	Sleep, x
	Send, {LButton Up}{w up}{a up}
}
