### ISSUE TITLE
help

### ISSUE THREAD

**Issue by fractured345** [sSteps1s/Netherwart-Macro#4]
were do i run it and what do i down load

**Comment by maxsonchen** [comment]
First you will neek to download Auto Hot Key 
[https://www.autohotkey.com/](url)

Then you can download the file for this macro and unzip it
Next you have to change the timing in the code which will be the Sleep, (your amount) to the time it takes for you to go from one side of the farm to the other.
Finally you have to change the loop number, if you have an infinite farm just put a large number

**Comment by fractured345** [comment]
no result for search

**Comment by fractured345** [comment]
dosent show up
the auto hotkey

**Comment by maxsonchen** [comment]
Paste that link into your browser

**Comment by fractured345** [comment]
i got it

**Comment by maxsonchen** [comment]
Also please don't comment on other issues as I will get to yours within 12 hours

**Comment by fractured345** [comment]
sorry
ive bin looking all day

**Comment by maxsonchen** [comment]
When you are finished editing the script to suit your needs double click the script, go to hypixel and your farm and then in ur task bar where ur apps are right click the H symbol and press reload script. Then press Ctrl-Z and your macro will do the work for you

**Comment by fractured345** [comment]
now what do i do i got it downloaded
were do i put it in auto skript

**Comment by maxsonchen** [comment]
![image](https://user-images.githubusercontent.com/84909844/135958477-27a76d9d-e263-4387-a332-661d7fdab069.png)
It will look like the H here

**Comment by fractured345** [comment]
no there

**Comment by maxsonchen** [comment]
Sorry, can you explain a little bit more?

**Comment by fractured345** [comment]
i got it dont worry i loaded it

**Comment by maxsonchen** [comment]
You will need to configure it to the length of your farm and the speed which you will be running at

**Comment by fractured345** [comment]
were do yo upaste skript

**Comment by maxsonchen** [comment]
You don't paste the script, you download it from this repository as a zip file. As shown below
![image](https://user-images.githubusercontent.com/84909844/135958682-9987ddbb-517d-468a-a79c-e28f94d4ca5b.png)

Then you unzip the file and edit it

**Comment by fractured345** [comment]
ok then what do yo udo

**Comment by fractured345** [comment]
go it im skript line not most recently executed

**Comment by maxsonchen** [comment]
Did you unzip the file?

**Comment by fractured345** [comment]
Script lines most recently executed (oldest first).  Press [F5] to refresh.  The seconds elapsed between a line and the one after it is in parentheses to the right (if not 0).  The bottommost line's elapsed time is the number of seconds since it executed.

**Comment by fractured345** [comment]
thats what it says

**Comment by fractured345** [comment]
also how do yo udisable munlock

**Comment by fractured345** [comment]
sorry if im dumb

**Comment by maxsonchen** [comment]
Can you take a screenshot of the error please

**Comment by maxsonchen** [comment]
The script will also run of Ctrl-Z and not Function

**Comment by fractured345** [comment]
![Screenshot (501)](https://user-images.githubusercontent.com/89229998/135959517-42d41df4-0cd4-475d-a5a2-1a0766996235.png)

**Comment by maxsonchen** [comment]
You can close that tab. In your taskbar there should be the H which I showed earlier. When you are in the game right click the H and press reload, then press Ctrl-Z

**Comment by fractured345** [comment]
ok

**Comment by fractured345** [comment]
do i to be in hypixel

**Comment by maxsonchen** [comment]
BTW what is your IGN in Hypixel, I can visit you and configure the script for you.

**Comment by maxsonchen** [comment]
Yes, for the script to farm netherwart you have to be in hypixel

**Comment by fractured345** [comment]
can i run this on more then one acount at a time

**Comment by maxsonchen** [comment]
Yes, but you need to have the script downloaded on the machine which you will be executing this on

**Comment by fractured345** [comment]
how do i do that

**Comment by maxsonchen** [comment]
Will you be using multiple devices for the different accounts?

**Comment by fractured345** [comment]
no just one

**Comment by maxsonchen** [comment]
You can't run on multiple accounts then

**Comment by fractured345** [comment]
ok

**Comment by maxsonchen** [comment]
What is ur IGN? I will visit you and edit the script for your farm. Also do you have rancher boots?

**Comment by fractured345** [comment]
ya not on this alt tho

**Comment by maxsonchen** [comment]
Will you be using the rancher boots to farm? As your speed will effect the time it takes to go from one side to the other

**Comment by fractured345** [comment]
ya

**Comment by maxsonchen** [comment]
What is your IGN? I will configure the script to your farm with rancher boots for 145% speed

**Comment by fractured345** [comment]
my farms goin to be 80 block long

**Comment by fractured345** [comment]
havent built it

**Comment by maxsonchen** [comment]
It is based of milliseconds not speed per block

**Comment by maxsonchen** [comment]
Why r u looking for a macro without building your farm?

**Comment by fractured345** [comment]
cause havent done it on alt

**Comment by fractured345** [comment]
can yo uconfig it to 80 blocks long

**Comment by fractured345** [comment]
aresu312

**Comment by fractured345** [comment]
ign

**Comment by maxsonchen** [comment]
I could probably configure it to 80 blocks long by working out the speed per block in milliseconds with rancher boots of 145% speed

**Comment by fractured345** [comment]
i dont neeed to us erancher boots if thats easyer

**Comment by maxsonchen** [comment]
It is easier to use rancher boots as otherwise speed differs between profiles

**Comment by fractured345** [comment]
ok

**Comment by maxsonchen** [comment]
Just a note your farm should be a vertical farm

**Comment by fractured345** [comment]
so can yo uconfig

**Comment by maxsonchen** [comment]
Yes

**Comment by maxsonchen** [comment]
I can make a rough code which should work but may not be perfect. This can be edited later when you have built your farm

**Comment by maxsonchen** [comment]
Sorry 245% speed

**Comment by fractured345** [comment]
ok

**Comment by fractured345** [comment]
thx

**Comment by fractured345** [comment]
Set up farm via an 8 by x rectangle of soul sand, and for each row of soul sand, place a fence two blocks above the soul sand for all but the soul sand on the left. Surround everything with cobblestone.

**Comment by fractured345** [comment]
what would this farm look like

**Comment by maxsonchen** [comment]
A vertical netherwart farm should look something similar to SweetBootie farm

**Comment by fractured345** [comment]
ok

**Comment by maxsonchen** [comment]
https://www.youtube.com/watch?v=SWcjfwFR1dU

It should be something like this, you don't need the redstone

**Comment by fractured345** [comment]
ok\

**Comment by fractured345** [comment]
can yuo hid ethgis from other people this conversation

**Comment by maxsonchen** [comment]
I have locked the conversation

**Comment by maxsonchen** [comment]
I will try hide it

**Comment by maxsonchen** [comment]
There is no way for me to lock it without closing the issue

**Comment by fractured345** [comment]
ok

**Comment by maxsonchen** [comment]
I have made a script for your farm

**Comment by fractured345** [comment]
ok thx

**Comment by fractured345** [comment]
say i pay like 40 dollars could you make a skript that i can tab out on can has restart prot

**Comment by maxsonchen** [comment]
Can you explain a bit more please. Give a few more details on what you want the script to do

**Comment by fractured345** [comment]
so i canpress windows and go to a dffrent tab and it still runs

**Comment by fractured345** [comment]
so i can run more then one acccount

**Comment by maxsonchen** [comment]
I will have to look more into the api and scripting but I will get back to you soon

**Comment by maxsonchen** [comment]
How can you run two instances of minecraft from one machine?

**Comment by fractured345** [comment]
ya
i can but i neeed a macro taht will run on each window so i can do it on one machine

**Comment by fractured345** [comment]
like say i got 3 minecraft accounts logged in they all can macro at once

**Comment by fractured345** [comment]
if you have 2 accounts you can

**Comment by fractured345** [comment]
be nice to here from you

**Comment by fractured345** [comment]
@sSteps1s

**Comment by maxsonchen** [comment]
bro can u not spam these replies

**Comment by maxsonchen** [comment]
ahk works on ur window as a whole not in seperate tabs the only way to make ahk run on one machine would be to create mmultiple instances such as vm

**Comment by fractured345** [comment]
how yo udo taht cause ive seen people do more then one account and just tab out

**Comment by fractured345** [comment]
could yo udo it

**Comment by fractured345** [comment]
no on seperate tabs

**Comment by fractured345** [comment]
so i can have one tab going then i can tab to another and it still runs

**Comment by fractured345** [comment]
@sSteps1s

**Comment by fractured345** [comment]
cause ill pay you to help me get set up

**Comment by maxsonchen** [comment]
You can probably do it with other scripting languages such as python and java but at the moment I use ahk which doesn't have the necessary api which is required to tab out to other apps without vm

**Comment by fractured345** [comment]
i can get vm or do yo know ill still pay youfor takeing him to him a person

**Comment by fractured345** [comment]
do yo uknow were i can get it

**Comment by maxsonchen** [comment]
what?

**Comment by fractured345** [comment]
sorry 
how do i get vm or do you know a person who can do it if so ill pay you to get me to him

**Comment by fractured345** [comment]
or were can i get get a tab out skript

**Comment by maxsonchen** [comment]
I make scripts for fun, I am not involved with community projects or have looked for source code to help make the script which you are looking for. I'm sorry but I cannot help u, I am also not qualified enough in using vm accurately as I only use it for personal uses.

**Comment by fractured345** [comment]
do you know a person taht can do it it will help me soooo much ill pay you

**Comment by fractured345** [comment]
or put me in a derection

**Comment by maxsonchen** [comment]
I could make scripts to that calibre using different code ect but I am a student and have exams to focus on and as I said before this project was for fun.

**Comment by fractured345** [comment]
ok
thx tho if yo uknwop a person or a discor dsever pls bro pls

**Comment by fractured345** [comment]
pls

**Comment by fractured345** [comment]
yo udont hav eno one

**Comment by fractured345** [comment]
@sSteps1s
